services:
  web:
    build: .
    container_name: appcontainer
    ports:
      - 3001:3001
    expose:
      - 3001
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: 'root'
      DB_PASS: 
      DB_NAME: inventory_api
      PORT: 3001
    depends_on:
      - db
    networks:
      - appnetwork

  db:
    image: mysql:8.0
    container_name: mysqlcontainer
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: inventory_api
    ports:
      - $DB_PORT:$DB_DOCKER_PORT
    expose:
      - 3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - appnetwork

volumes:
  db_data:
networks:
  appnetwork:
    driver: bridge
